spring:
  servlet:
    # file upload
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: springboot-portal
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hairroom
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
    password: 12345678

server:
  port: 8081
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #不开启数据库下划线到驼峰的转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#支付宝
alipay:
  appId: 9021000138638077
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzc/sBAANPM6+n77HTmpqfvCo/dpVSqyuESMZk6eUjVo5IVQuidffv7Fub+ocE+kzccuuFEMbaZJsSrYz2yM5vHEO+/Uytp60af9uikUD8DN9slFlyoGttWzXB0PLOrgrR+4ZFscMid5dCizxjKVm+rSduO6p34JvqR4ULHBGl0OnLnxP+dSB03DcJXuLZlMy1HVX/fSb/3kxZxZg2ZVDEjtwS5qis2mpJWGR//RkFUS8F2QblEdLAm7Ij9b7LBcQJgZtmhQsu/jVtW2VddIqJfMfjDnejvkrTBeK6OqEEk3ggGbFyXflJziNaoW4lVq5avU6+TnP1EUfOMbiMocTZAgMBAAECggEAZRoz0TVrp+Sr00a0/k29Tb9aYhTyPfgX9Vh3BgXMxeMPGGtpuacTAAY++prkFQbb5NuOG5L/Ja3GvHgw0h0CSRE4jdLxr2inmyVr3aROY3LxMaBG4NDGlX7sw3xwP8dIa1N1K7DiCnosKx588DUszcOKUo2lFhLiZNTUfRTcUHl2LD5V6m2MDSLSJD9ylQm4h2DqqE2bQwP9evmEt/ZsacaBivJqZrsgpRxlH2bwhd24sj9x89cU8/2SQLzDqFIgbDSnFMb8RRZprOdH46A0qQddnXF8YRTv5GWzdwaquN6mGzXYNbF3FKC1RGOczVPcufkmxD3slsBB41zFqPKQsQKBgQD3cxBi2mLuGxIKZ7WLbdSjv1PPG2ga+ARFPykmMdJ3oKhCpNOKyY7cnNIqKJrSDeG5GWbKyaej1J9TScWUGD1S+oHawP+3LTNC2yaUbPRD2Jmx4YWKjTytLDI2V3JwmtLMllyVkHqaeIIZoZ+YCmkflMvAa9p43pdgaWhbujtLRQKBgQC5p2uywEa034q2I92c+Q6dJDsKGJm5/3euhE2WbbBqlGbe+an/cw+1hnBthlRD867JM0T3MAjI+S7rfHaJm761gJZphOYhmBiYgvzoNyFkK4DNIYLBtX4irfNBd/ZjQ/aa0Ncs5mducdcUfxY52w2oosAxO3NJ5PytHx2fl4qihQKBgDm/6eAYNaR6PuCcyZrLvCenHGkmbUp1/ZEnp3PZhtQSc5JyI0itt6C3HLloFpHVWYu4aOwE2hH7Kl/mxKzGZ3F5M1sZVdSrQN5mhP942h0HbP89scvfIH0N5n4WNIghKfdDVEI3oNVyMHLI7JUwQM51DIRQ54Dz+gIvN4LI2NO9AoGAGK6qgdxQSjHCFk8UYo82Iywy8TeuEG1ncvtB+XLh1nmeZ5yXvk+E0iRqhBUs1M/r9/HqBFcNg/KlC0fD1q2vICBVXvf9RJAdDQG1MAZMWS3zdNI0uR4xA9lOkvCpAC+D9Lc5NE35iFR4PNBcmxqFaVsh5Cm8PSHFehq97H7QPqUCgYEA64JrgUw7KKjB4utYtoLzfu4QCyJQvRd2gos9HMv3MdcroRJAezZ1F3D6qiFQmwC18T9UOQlR/WjoA/+YhC5c2Ff9fI7gafHJXCDeY5mx3UTOt150zQ+3sBedGAjGMLjYYDsult1L57/THJGbdHHFpato7wTfAg5gs3ce/dPqTWE=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjXyq1N3+HS2t0Ppfa/aA96UcwgSmKeGqGFuKqmjqf4++8/750xOnuMugK5cWd7kGZPV4nGEG0vmuEDAkdiCYW9G7E5lknIalOolvJH3r6PmyEIIcLqnYlduQsTtdPfr5+MHxv+ZLEPUSBCYaNefpFZscW/LQ1GmiEVXrtGuyb9svG2sX5UTSMqcNuosmclacsxJJOGzM+ty2iQEqxKQ0b6l25ci7r8I3CjE6VaGSQCMv8FdGC8Mhy0B6V9Xct3/+7cuJDhr6db3QxgmfG1jvcid5shlQpuaT2GTg1OWSjw48+BMq+GQmrWUjFF+94pFDDO2Uqkzc/fqu8ZhrtQlLZwIDAQAB
  notifyUrl:
  returnUrl: